version: '3.8'
services:

  # Anomaly Detector
  # ============================================================================
  # Anomaly Detector
  anomaly-detector:
    build: ./docker/anomaly-detector
    image: pad/anomaly-detector-prometheus
    container_name: anomaly-detector-prometheus
    environment:
      - FLT_PROM_URL=http://192.168.88.251:9090
      - FLT_PROM_ACCESS_TOKEN=
      - FLT_METRICS_LIST=process_cpu_usage{service='admin-server'}
      - FLT_RETRAINING_INTERVAL_MINUTES=15
      - FLT_ROLLING_TRAINING_WINDOW_SIZE=15d
      - FLT_DEBUG_MODE=True
      - APP_FILE=/pad/app.py
    #entrypoint: ["sh", "-c","
    #  ./dockerize -wait=tcp://discovery-server:8761 \
    #              -wait=tcp://ocelot-config-server:8090 \
    #              -wait=tcp://influxdb-server:8086 \
    #              -wait=tcp://tracing-server:9411  \
    #              -timeout=300s -- &&
    #  java -XX:+UnlockExperimentalVMOptions -Djava.security.egd=file:/dev/./urandom
    #  -javaagent:/agent/inspectit-ocelot-agent.jar
    #  org.springframework.boot.loader.JarLauncher"]
    volumes:
      - .:/pad
    ports:
      - 8080:8080
