# my global config
global:
  scrape_interval: 15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

scrape_configs:
- job_name: 'anomaly-detection'
  static_configs:
  - targets: ['anomaly-detector:8080']
    labels:
      host: 'anomaly-detector'
