{
 "title": "Anomaly Detetion",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "service", "query": "label_values(service)" }
  ]
 },
 "panels": [
  { "title": "$service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "service" },
  {
   "title": "Process CPU Anomaly Detection",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "process_cpu_usage_prophet{service=\"$service\", value_type=\"yhat_upper\"}",
     "legendFormat": "yhat_upper",
     "query": "from(bucket: \"telegraf\")\n|> range($range)\n|> filter(fn: (r) =>\n  r._measurement == \"process_cpu_usage\" AND\n  r.service == \"$service\" AND\n  r._field == \"gauge\")\n|> keep(columns: [\"_value\", \"_time\", \"_measurement\"])"
    },
    {
     "expr": "process_cpu_usage_prophet{service=\"$service\", value_type=\"yhat\"}",
     "legendFormat": "yhat",
     "query": "from(bucket: \"telegraf\")\n|> range($range)\n|> filter(fn: (r) =>\n  r._measurement == \"system_cpu_usage\" AND\n  r.service == \"$service\" AND\n  r._field == \"gauge\")\n|> keep(columns: [\"_value\", \"_time\", \"_measurement\"])\n"
    },
    {
     "expr": "process_cpu_usage_prophet{service=\"$service\", value_type=\"yhat_lower\"}",
     "legendFormat": "yhat_lower"
    },
    {
     "expr": "process_cpu_usage_prophet{service=\"$service\", value_type=\"anomaly\"}",
     "legendFormat": "anomaly"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 }, "content": "----" },
  {
   "title": "$service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "graph",
     "gridPos": { "h": 6, "w": 7, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "process_cpu_usage{service=\"$service\"}",
       "legendFormat": "process_cpu_usage",
       "query": "from(bucket: \"telegraf\")\n|> range($range)\n|> filter(fn: (r) =>\n  r._measurement == \"process_cpu_usage\" AND\n  r.service == \"$service\" AND\n  r._field == \"gauge\")\n|> keep(columns: [\"_value\", \"_time\", \"_measurement\"])"
      },
      {
       "expr": "system_cpu_usage{service=\"$service\"}",
       "legendFormat": "system_cpu_usage",
       "query": "from(bucket: \"telegraf\")\n|> range($range)\n|> filter(fn: (r) =>\n  r._measurement == \"system_cpu_usage\" AND\n  r.service == \"$service\" AND\n  r._field == \"gauge\")\n|> keep(columns: [\"_value\", \"_time\", \"_measurement\"])\n"
      }
     ]
    },
    {
     "title": "Memory - Heap",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 7, "y": 13 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "max",
       "expr": "sum(jvm_memory_max{service=\"$service\", area=\"heap\"})",
       "groupBy": [
        { "params": [ "15s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "max",
       "measurement": "jvm_memory_max",
       "query": "SELECT mean(\"gauge\") FROM \"jvm_memory_max\" WHERE (\"service\" =~ /^$service$/) AND $timeFilter GROUP BY time(1m) fill(null)",
       "select": [
        [
         { "params": [ "gauge" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "service", "operator": "=~", "value": "/^$service$/" },
        { "condition": "AND", "key": "area", "operator": "=", "value": "heap" }
       ]
      },
      {
       "alias": "committed",
       "expr": "sum(jvm_memory_committed{service=\"$service\", area=\"heap\"})",
       "groupBy": [
        { "params": [ "15s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "committed",
       "measurement": "jvm_memory_committed",
       "query": "SELECT mean(\"gauge\") FROM \"jvm_memory_max\" WHERE (\"service\" =~ /^$service$/) AND $timeFilter GROUP BY time(1m) fill(null)",
       "select": [
        [
         { "params": [ "gauge" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "service", "operator": "=~", "value": "/^$service$/" },
        { "condition": "AND", "key": "area", "operator": "=", "value": "heap" }
       ]
      },
      {
       "alias": "used",
       "expr": "sum(jvm_memory_used{service=\"$service\", area=\"heap\"})",
       "groupBy": [
        { "params": [ "15s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "used",
       "measurement": "jvm_memory_used",
       "query": "SELECT mean(\"gauge\") FROM \"jvm_memory_max\" WHERE (\"service\" =~ /^$service$/) AND $timeFilter GROUP BY time(1m) fill(null)",
       "select": [
        [
         { "params": [ "gauge" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "service", "operator": "=~", "value": "/^$service$/" },
        { "condition": "AND", "key": "area", "operator": "=", "value": "heap" }
       ]
      }
     ]
    },
    {
     "title": "# Live Threads",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 13, "y": 13 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "jvm_threads_daemon{service=\"$service\"}",
       "legendFormat": "daemon",
       "query": "from(bucket: \"telegraf\")\n|> range($range)\n|> filter(fn: (r) =>\n  r._measurement == \"jvm_threads_daemon\" AND\n  r.service == \"$service\" AND\n  r._field == \"gauge\")\n|> map(fn:(r) => ({\n        _time: r._time,\n        _value: r._value,\n        _measurement: \"daemon\"\n    }))\n|> keep(columns: [\"_value\", \"_time\", \"_measurement\"])"
      },
      {
       "alias": "$tag_state",
       "expr": "jvm_threads_live{service=\"$service\"} - jvm_threads_daemon{service=\"$service\"}",
       "groupBy": [
        { "params": [ "15s" ], "type": "time" },
        { "params": [ "state" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "non-deamon",
       "measurement": "jvm_threads_states",
       "query": "lnd = () => {\nlive = from(bucket: \"telegraf\")\n|> range($range)\n|> filter(fn: (r) =>\n  r._measurement == \"jvm_threads_live\" AND\n  r.service == \"$service\" AND\n  r._field == \"gauge\")\n|> keep(columns: [\"_value\", \"_time\", \"_measurement\"])\n  \ndaemon = from(bucket: \"telegraf\")\n|> range($range)\n|> filter(fn: (r) =>\n  r._measurement == \"jvm_threads_daemon\" AND\n  r.service == \"$service\" AND\n  r._field == \"gauge\")\n|> keep(columns: [\"_value\", \"_time\", \"_measurement\"])\n  \nreturn join(tables:{live:live, daemon:daemon},on:[\"_time\",\"_stop\",\"_start\", \"host\"])\n    |> map(fn:(r) => ({\n        _time: r._time,\n        _value: (r._value_live - r._value_daemon),\n        _measurement: \"non-daemon\"\n    }))\n}\n\nlnd()",
       "select": [
        [
         { "params": [ "gauge" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "service", "operator": "=~", "value": "/^$service$/" }
       ]
      },
      {
       "expr": "jvm_threads_peak{service=\"$service\"} - jvm_threads_live{service=\"$service\"}",
       "legendFormat": "peak",
       "query": "stackedPeak = () => {\npeak = from(bucket: \"telegraf\")\n|> range($range)\n|> filter(fn: (r) =>\n  r._measurement == \"jvm_threads_peak\" AND\n  r.service == \"$service\" AND\n  r._field == \"gauge\")\n|> keep(columns: [\"_value\", \"_time\", \"_measurement\"])\n\nlive = from(bucket: \"telegraf\")\n|> range($range)\n|> filter(fn: (r) =>\n  r._measurement == \"jvm_threads_live\" AND\n  r.service == \"$service\" AND\n  r._field == \"gauge\")\n|> keep(columns: [\"_value\", \"_time\", \"_measurement\"])\n  \n\n  \nreturn join(tables:{live:live, peak:peak},on:[\"_time\",\"_stop\",\"_start\", \"host\"])\n    |> map(fn:(r) => ({\n        _time: r._time,\n        _value: (r._value_peak - r._value_live),\n        _measurement: \"peak\"\n    }))\n}\n\nstackedPeak()"
      }
     ]
    },
    {
     "title": "Garbage Collection Memory",
     "type": "graph",
     "gridPos": { "h": 6, "w": 5, "x": 19, "y": 13 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "Live Data Size",
       "expr": "jvm_gc_live_data_size{service=\"$service\"}",
       "groupBy": [
        { "params": [ "15s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Live Data Size",
       "measurement": "jvm_gc_live_data_size",
       "query": "SELECT \"gauge\" FROM \"jvm_gc_live_data_size\" WHERE (\"service\" =~ /^$service$/) ",
       "select": [
        [
         { "params": [ "gauge" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "service", "operator": "=~", "value": "/^$service$/" }
       ]
      },
      {
       "alias": "Max Data Size",
       "expr": "jvm_gc_max_data_size{service=\"$service\"}",
       "groupBy": [
        { "params": [ "15s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Max Data Size",
       "measurement": "jvm_gc_max_data_size",
       "query": "SELECT \"gauge\" FROM \"jvm_gc_live_data_size\" WHERE (\"service\" =~ /^$service$/) ",
       "select": [
        [
         { "params": [ "gauge" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "service", "operator": "=~", "value": "/^$service$/" }
       ]
      },
      {
       "alias": "Allocated Memory",
       "expr": "idelta(jvm_gc_memory_allocated{service=\"$service\"}[$__range])",
       "groupBy": [
        { "params": [ "15s" ], "type": "time" }
       ],
       "legendFormat": "Allocated Memory",
       "measurement": "jvm_gc_memory_allocated",
       "query": "SELECT difference(sum(\"counter\")) FROM \"jvm_gc_memory_allocated\" WHERE (\"service\" =~ /^$service$/) AND $timeFilter GROUP BY time(15s)",
       "select": [
        [
         { "params": [ "counter" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         {
          "params": [],
          "type": "non_negative_difference"
         }
        ]
       ],
       "tags": [
        { "key": "service", "operator": "=~", "value": "/^$service$/" }
       ]
      },
      {
       "alias": "Promoted Memory",
       "expr": "idelta(jvm_gc_memory_promoted{service=\"$service\"}[$__range])",
       "groupBy": [
        { "params": [ "15s" ], "type": "time" }
       ],
       "legendFormat": "Promoted Memory",
       "measurement": "jvm_gc_memory_promoted",
       "query": "SELECT difference(sum(\"counter\")) FROM \"jvm_gc_memory_allocated\" WHERE (\"service\" =~ /^$service$/) AND $timeFilter GROUP BY time(15s)",
       "select": [
        [
         { "params": [ "counter" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         {
          "params": [],
          "type": "non_negative_difference"
         }
        ]
       ],
       "tags": [
        { "key": "service", "operator": "=~", "value": "/^$service$/" }
       ]
      }
     ]
    },
    {
     "title": "Current CPU Usage",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 19 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "expr": "process_cpu_usage{service=\"$service\"}",
       "measurement": "process_cpu_usage",
       "select": [
        [
         { "params": [ "gauge" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "service", "operator": "=~", "value": "/^$service$/" }
       ]
      }
     ]
    },
    {
     "title": "Loaded Classes",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 4, "y": 19 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "jvm_classes_loaded{service=\"$service\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "from(bucket: \"telegraf\")\n  |> range(start: -1m)\n  |> filter(fn: (r) =>\n    r._measurement == \"jvm_classes_loaded\" AND\n    r.service == \"$service\" AND\n    r._field == \"gauge\")\n  |> keep(columns: [\"_value\", \"_time\", \"service\"])\n  |> last()\n",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Memory - Non-Heap",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 7, "y": 19 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "max",
       "expr": "sum(jvm_memory_max{service=\"$service\", area=\"nonheap\"})",
       "groupBy": [
        { "params": [ "15s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "max",
       "measurement": "jvm_memory_max",
       "query": "SELECT mean(\"gauge\") FROM \"jvm_memory_max\" WHERE (\"service\" =~ /^$service$/) AND $timeFilter GROUP BY time(1m) fill(null)",
       "select": [
        [
         { "params": [ "gauge" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "service", "operator": "=~", "value": "/^$service$/" },
        { "condition": "AND", "key": "area", "operator": "=", "value": "nonheap" }
       ]
      },
      {
       "alias": "committed",
       "expr": "sum(jvm_memory_committed{service=\"$service\", area=\"nonheap\"})",
       "groupBy": [
        { "params": [ "15s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "committed",
       "measurement": "jvm_memory_committed",
       "query": "SELECT mean(\"gauge\") FROM \"jvm_memory_max\" WHERE (\"service\" =~ /^$service$/) AND $timeFilter GROUP BY time(1m) fill(null)",
       "select": [
        [
         { "params": [ "gauge" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "service", "operator": "=~", "value": "/^$service$/" },
        { "condition": "AND", "key": "area", "operator": "=", "value": "nonheap" }
       ]
      },
      {
       "alias": "used",
       "expr": "sum(jvm_memory_used{service=\"$service\", area=\"nonheap\"})",
       "groupBy": [
        { "params": [ "15s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "used",
       "measurement": "jvm_memory_used",
       "query": "SELECT mean(\"gauge\") FROM \"jvm_memory_max\" WHERE (\"service\" =~ /^$service$/) AND $timeFilter GROUP BY time(1m) fill(null)",
       "select": [
        [
         { "params": [ "gauge" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "service", "operator": "=~", "value": "/^$service$/" },
        { "condition": "AND", "key": "area", "operator": "=", "value": "nonheap" }
       ]
      }
     ]
    },
    {
     "title": "# Threads by States",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 13, "y": 19 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "$tag_state",
       "expr": "jvm_threads_states{service=\"$service\"}",
       "groupBy": [
        { "params": [ "15s" ], "type": "time" },
        { "params": [ "state" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{state}}",
       "measurement": "jvm_threads_states",
       "query": "SELECT mean(\"gauge\") FROM \"jvm_memory_max\" WHERE (\"service\" =~ /^$service$/) AND $timeFilter GROUP BY time(1m) fill(null)",
       "select": [
        [
         { "params": [ "gauge" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "service", "operator": "=~", "value": "/^$service$/" }
       ]
      }
     ]
    },
    {
     "title": "Garbage Collection Pauses",
     "type": "graph",
     "gridPos": { "h": 6, "w": 5, "x": 19, "y": 19 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "sum(idelta(jvm_gc_pause{service=\"$service\", action=\"end of minor GC\"}[$__range]))",
       "legendFormat": "Minor GC"
      },
      {
       "expr": "idelta(jvm_gc_pause{service=\"$service\", action=\"end of major GC\"}[$__range])",
       "legendFormat": "Major GC"
      }
     ]
    },
    {
     "title": "Unloaded Classes",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 4, "y": 22 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "jvm_classes_unloaded{service=\"$service\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "from(bucket: \"telegraf\")\n  |> range(start: -1m)\n  |> filter(fn: (r) =>\n    r._measurement == \"jvm_classes_unloaded\" AND\n    r.service == \"$service\" AND\n    r._field == \"gauge\")\n  |> keep(columns: [\"_value\", \"_time\", \"service\"])\n  |> last()\n",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    { "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 }, "content": "----" }
   ]
  },
  {
   "title": "$service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "graph",
     "gridPos": { "h": 6, "w": 7, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "process_cpu_usage{service=\"$service\"}",
       "legendFormat": "process_cpu_usage",
       "query": "from(bucket: \"telegraf\")\n|> range($range)\n|> filter(fn: (r) =>\n  r._measurement == \"process_cpu_usage\" AND\n  r.service == \"$service\" AND\n  r._field == \"gauge\")\n|> keep(columns: [\"_value\", \"_time\", \"_measurement\"])"
      },
      {
       "expr": "system_cpu_usage{service=\"$service\"}",
       "legendFormat": "system_cpu_usage",
       "query": "from(bucket: \"telegraf\")\n|> range($range)\n|> filter(fn: (r) =>\n  r._measurement == \"system_cpu_usage\" AND\n  r.service == \"$service\" AND\n  r._field == \"gauge\")\n|> keep(columns: [\"_value\", \"_time\", \"_measurement\"])\n"
      }
     ]
    },
    {
     "title": "Memory - Heap",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 7, "y": 16 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "max",
       "expr": "sum(jvm_memory_max{service=\"$service\", area=\"heap\"})",
       "groupBy": [
        { "params": [ "15s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "max",
       "measurement": "jvm_memory_max",
       "query": "SELECT mean(\"gauge\") FROM \"jvm_memory_max\" WHERE (\"service\" =~ /^$service$/) AND $timeFilter GROUP BY time(1m) fill(null)",
       "select": [
        [
         { "params": [ "gauge" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "service", "operator": "=~", "value": "/^$service$/" },
        { "condition": "AND", "key": "area", "operator": "=", "value": "heap" }
       ]
      },
      {
       "alias": "committed",
       "expr": "sum(jvm_memory_committed{service=\"$service\", area=\"heap\"})",
       "groupBy": [
        { "params": [ "15s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "committed",
       "measurement": "jvm_memory_committed",
       "query": "SELECT mean(\"gauge\") FROM \"jvm_memory_max\" WHERE (\"service\" =~ /^$service$/) AND $timeFilter GROUP BY time(1m) fill(null)",
       "select": [
        [
         { "params": [ "gauge" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "service", "operator": "=~", "value": "/^$service$/" },
        { "condition": "AND", "key": "area", "operator": "=", "value": "heap" }
       ]
      },
      {
       "alias": "used",
       "expr": "sum(jvm_memory_used{service=\"$service\", area=\"heap\"})",
       "groupBy": [
        { "params": [ "15s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "used",
       "measurement": "jvm_memory_used",
       "query": "SELECT mean(\"gauge\") FROM \"jvm_memory_max\" WHERE (\"service\" =~ /^$service$/) AND $timeFilter GROUP BY time(1m) fill(null)",
       "select": [
        [
         { "params": [ "gauge" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "service", "operator": "=~", "value": "/^$service$/" },
        { "condition": "AND", "key": "area", "operator": "=", "value": "heap" }
       ]
      }
     ]
    },
    {
     "title": "# Live Threads",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 13, "y": 16 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "jvm_threads_daemon{service=\"$service\"}",
       "legendFormat": "daemon",
       "query": "from(bucket: \"telegraf\")\n|> range($range)\n|> filter(fn: (r) =>\n  r._measurement == \"jvm_threads_daemon\" AND\n  r.service == \"$service\" AND\n  r._field == \"gauge\")\n|> map(fn:(r) => ({\n        _time: r._time,\n        _value: r._value,\n        _measurement: \"daemon\"\n    }))\n|> keep(columns: [\"_value\", \"_time\", \"_measurement\"])"
      },
      {
       "alias": "$tag_state",
       "expr": "jvm_threads_live{service=\"$service\"} - jvm_threads_daemon{service=\"$service\"}",
       "groupBy": [
        { "params": [ "15s" ], "type": "time" },
        { "params": [ "state" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "non-deamon",
       "measurement": "jvm_threads_states",
       "query": "lnd = () => {\nlive = from(bucket: \"telegraf\")\n|> range($range)\n|> filter(fn: (r) =>\n  r._measurement == \"jvm_threads_live\" AND\n  r.service == \"$service\" AND\n  r._field == \"gauge\")\n|> keep(columns: [\"_value\", \"_time\", \"_measurement\"])\n  \ndaemon = from(bucket: \"telegraf\")\n|> range($range)\n|> filter(fn: (r) =>\n  r._measurement == \"jvm_threads_daemon\" AND\n  r.service == \"$service\" AND\n  r._field == \"gauge\")\n|> keep(columns: [\"_value\", \"_time\", \"_measurement\"])\n  \nreturn join(tables:{live:live, daemon:daemon},on:[\"_time\",\"_stop\",\"_start\", \"host\"])\n    |> map(fn:(r) => ({\n        _time: r._time,\n        _value: (r._value_live - r._value_daemon),\n        _measurement: \"non-daemon\"\n    }))\n}\n\nlnd()",
       "select": [
        [
         { "params": [ "gauge" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "service", "operator": "=~", "value": "/^$service$/" }
       ]
      },
      {
       "expr": "jvm_threads_peak{service=\"$service\"} - jvm_threads_live{service=\"$service\"}",
       "legendFormat": "peak",
       "query": "stackedPeak = () => {\npeak = from(bucket: \"telegraf\")\n|> range($range)\n|> filter(fn: (r) =>\n  r._measurement == \"jvm_threads_peak\" AND\n  r.service == \"$service\" AND\n  r._field == \"gauge\")\n|> keep(columns: [\"_value\", \"_time\", \"_measurement\"])\n\nlive = from(bucket: \"telegraf\")\n|> range($range)\n|> filter(fn: (r) =>\n  r._measurement == \"jvm_threads_live\" AND\n  r.service == \"$service\" AND\n  r._field == \"gauge\")\n|> keep(columns: [\"_value\", \"_time\", \"_measurement\"])\n  \n\n  \nreturn join(tables:{live:live, peak:peak},on:[\"_time\",\"_stop\",\"_start\", \"host\"])\n    |> map(fn:(r) => ({\n        _time: r._time,\n        _value: (r._value_peak - r._value_live),\n        _measurement: \"peak\"\n    }))\n}\n\nstackedPeak()"
      }
     ]
    },
    {
     "title": "Garbage Collection Memory",
     "type": "graph",
     "gridPos": { "h": 6, "w": 5, "x": 19, "y": 16 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "Live Data Size",
       "expr": "jvm_gc_live_data_size{service=\"$service\"}",
       "groupBy": [
        { "params": [ "15s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Live Data Size",
       "measurement": "jvm_gc_live_data_size",
       "query": "SELECT \"gauge\" FROM \"jvm_gc_live_data_size\" WHERE (\"service\" =~ /^$service$/) ",
       "select": [
        [
         { "params": [ "gauge" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "service", "operator": "=~", "value": "/^$service$/" }
       ]
      },
      {
       "alias": "Max Data Size",
       "expr": "jvm_gc_max_data_size{service=\"$service\"}",
       "groupBy": [
        { "params": [ "15s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Max Data Size",
       "measurement": "jvm_gc_max_data_size",
       "query": "SELECT \"gauge\" FROM \"jvm_gc_live_data_size\" WHERE (\"service\" =~ /^$service$/) ",
       "select": [
        [
         { "params": [ "gauge" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "service", "operator": "=~", "value": "/^$service$/" }
       ]
      },
      {
       "alias": "Allocated Memory",
       "expr": "idelta(jvm_gc_memory_allocated{service=\"$service\"}[$__range])",
       "groupBy": [
        { "params": [ "15s" ], "type": "time" }
       ],
       "legendFormat": "Allocated Memory",
       "measurement": "jvm_gc_memory_allocated",
       "query": "SELECT difference(sum(\"counter\")) FROM \"jvm_gc_memory_allocated\" WHERE (\"service\" =~ /^$service$/) AND $timeFilter GROUP BY time(15s)",
       "select": [
        [
         { "params": [ "counter" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         {
          "params": [],
          "type": "non_negative_difference"
         }
        ]
       ],
       "tags": [
        { "key": "service", "operator": "=~", "value": "/^$service$/" }
       ]
      },
      {
       "alias": "Promoted Memory",
       "expr": "idelta(jvm_gc_memory_promoted{service=\"$service\"}[$__range])",
       "groupBy": [
        { "params": [ "15s" ], "type": "time" }
       ],
       "legendFormat": "Promoted Memory",
       "measurement": "jvm_gc_memory_promoted",
       "query": "SELECT difference(sum(\"counter\")) FROM \"jvm_gc_memory_allocated\" WHERE (\"service\" =~ /^$service$/) AND $timeFilter GROUP BY time(15s)",
       "select": [
        [
         { "params": [ "counter" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         {
          "params": [],
          "type": "non_negative_difference"
         }
        ]
       ],
       "tags": [
        { "key": "service", "operator": "=~", "value": "/^$service$/" }
       ]
      }
     ]
    },
    {
     "title": "Current CPU Usage",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 22 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "expr": "process_cpu_usage{service=\"$service\"}",
       "measurement": "process_cpu_usage",
       "select": [
        [
         { "params": [ "gauge" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "service", "operator": "=~", "value": "/^$service$/" }
       ]
      }
     ]
    },
    {
     "title": "Loaded Classes",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 4, "y": 22 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "jvm_classes_loaded{service=\"$service\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "from(bucket: \"telegraf\")\n  |> range(start: -1m)\n  |> filter(fn: (r) =>\n    r._measurement == \"jvm_classes_loaded\" AND\n    r.service == \"$service\" AND\n    r._field == \"gauge\")\n  |> keep(columns: [\"_value\", \"_time\", \"service\"])\n  |> last()\n",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Memory - Non-Heap",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 7, "y": 22 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "max",
       "expr": "sum(jvm_memory_max{service=\"$service\", area=\"nonheap\"})",
       "groupBy": [
        { "params": [ "15s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "max",
       "measurement": "jvm_memory_max",
       "query": "SELECT mean(\"gauge\") FROM \"jvm_memory_max\" WHERE (\"service\" =~ /^$service$/) AND $timeFilter GROUP BY time(1m) fill(null)",
       "select": [
        [
         { "params": [ "gauge" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "service", "operator": "=~", "value": "/^$service$/" },
        { "condition": "AND", "key": "area", "operator": "=", "value": "nonheap" }
       ]
      },
      {
       "alias": "committed",
       "expr": "sum(jvm_memory_committed{service=\"$service\", area=\"nonheap\"})",
       "groupBy": [
        { "params": [ "15s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "committed",
       "measurement": "jvm_memory_committed",
       "query": "SELECT mean(\"gauge\") FROM \"jvm_memory_max\" WHERE (\"service\" =~ /^$service$/) AND $timeFilter GROUP BY time(1m) fill(null)",
       "select": [
        [
         { "params": [ "gauge" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "service", "operator": "=~", "value": "/^$service$/" },
        { "condition": "AND", "key": "area", "operator": "=", "value": "nonheap" }
       ]
      },
      {
       "alias": "used",
       "expr": "sum(jvm_memory_used{service=\"$service\", area=\"nonheap\"})",
       "groupBy": [
        { "params": [ "15s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "used",
       "measurement": "jvm_memory_used",
       "query": "SELECT mean(\"gauge\") FROM \"jvm_memory_max\" WHERE (\"service\" =~ /^$service$/) AND $timeFilter GROUP BY time(1m) fill(null)",
       "select": [
        [
         { "params": [ "gauge" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "service", "operator": "=~", "value": "/^$service$/" },
        { "condition": "AND", "key": "area", "operator": "=", "value": "nonheap" }
       ]
      }
     ]
    },
    {
     "title": "# Threads by States",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 13, "y": 22 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "$tag_state",
       "expr": "jvm_threads_states{service=\"$service\"}",
       "groupBy": [
        { "params": [ "15s" ], "type": "time" },
        { "params": [ "state" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{state}}",
       "measurement": "jvm_threads_states",
       "query": "SELECT mean(\"gauge\") FROM \"jvm_memory_max\" WHERE (\"service\" =~ /^$service$/) AND $timeFilter GROUP BY time(1m) fill(null)",
       "select": [
        [
         { "params": [ "gauge" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "service", "operator": "=~", "value": "/^$service$/" }
       ]
      }
     ]
    },
    {
     "title": "Garbage Collection Pauses",
     "type": "graph",
     "gridPos": { "h": 6, "w": 5, "x": 19, "y": 22 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "sum(idelta(jvm_gc_pause{service=\"$service\", action=\"end of minor GC\"}[$__range]))",
       "legendFormat": "Minor GC"
      },
      {
       "expr": "idelta(jvm_gc_pause{service=\"$service\", action=\"end of major GC\"}[$__range])",
       "legendFormat": "Major GC"
      }
     ]
    },
    {
     "title": "Unloaded Classes",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 4, "y": 25 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "jvm_classes_unloaded{service=\"$service\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "from(bucket: \"telegraf\")\n  |> range(start: -1m)\n  |> filter(fn: (r) =>\n    r._measurement == \"jvm_classes_unloaded\" AND\n    r.service == \"$service\" AND\n    r._field == \"gauge\")\n  |> keep(columns: [\"_value\", \"_time\", \"service\"])\n  |> last()\n",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    { "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 }, "content": "----" }
   ]
  },
  {
   "title": "$service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "graph",
     "gridPos": { "h": 6, "w": 7, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "process_cpu_usage{service=\"$service\"}",
       "legendFormat": "process_cpu_usage",
       "query": "from(bucket: \"telegraf\")\n|> range($range)\n|> filter(fn: (r) =>\n  r._measurement == \"process_cpu_usage\" AND\n  r.service == \"$service\" AND\n  r._field == \"gauge\")\n|> keep(columns: [\"_value\", \"_time\", \"_measurement\"])"
      },
      {
       "expr": "system_cpu_usage{service=\"$service\"}",
       "legendFormat": "system_cpu_usage",
       "query": "from(bucket: \"telegraf\")\n|> range($range)\n|> filter(fn: (r) =>\n  r._measurement == \"system_cpu_usage\" AND\n  r.service == \"$service\" AND\n  r._field == \"gauge\")\n|> keep(columns: [\"_value\", \"_time\", \"_measurement\"])\n"
      }
     ]
    },
    {
     "title": "Memory - Heap",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 7, "y": 17 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "max",
       "expr": "sum(jvm_memory_max{service=\"$service\", area=\"heap\"})",
       "groupBy": [
        { "params": [ "15s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "max",
       "measurement": "jvm_memory_max",
       "query": "SELECT mean(\"gauge\") FROM \"jvm_memory_max\" WHERE (\"service\" =~ /^$service$/) AND $timeFilter GROUP BY time(1m) fill(null)",
       "select": [
        [
         { "params": [ "gauge" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "service", "operator": "=~", "value": "/^$service$/" },
        { "condition": "AND", "key": "area", "operator": "=", "value": "heap" }
       ]
      },
      {
       "alias": "committed",
       "expr": "sum(jvm_memory_committed{service=\"$service\", area=\"heap\"})",
       "groupBy": [
        { "params": [ "15s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "committed",
       "measurement": "jvm_memory_committed",
       "query": "SELECT mean(\"gauge\") FROM \"jvm_memory_max\" WHERE (\"service\" =~ /^$service$/) AND $timeFilter GROUP BY time(1m) fill(null)",
       "select": [
        [
         { "params": [ "gauge" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "service", "operator": "=~", "value": "/^$service$/" },
        { "condition": "AND", "key": "area", "operator": "=", "value": "heap" }
       ]
      },
      {
       "alias": "used",
       "expr": "sum(jvm_memory_used{service=\"$service\", area=\"heap\"})",
       "groupBy": [
        { "params": [ "15s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "used",
       "measurement": "jvm_memory_used",
       "query": "SELECT mean(\"gauge\") FROM \"jvm_memory_max\" WHERE (\"service\" =~ /^$service$/) AND $timeFilter GROUP BY time(1m) fill(null)",
       "select": [
        [
         { "params": [ "gauge" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "service", "operator": "=~", "value": "/^$service$/" },
        { "condition": "AND", "key": "area", "operator": "=", "value": "heap" }
       ]
      }
     ]
    },
    {
     "title": "# Live Threads",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 13, "y": 17 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "jvm_threads_daemon{service=\"$service\"}",
       "legendFormat": "daemon",
       "query": "from(bucket: \"telegraf\")\n|> range($range)\n|> filter(fn: (r) =>\n  r._measurement == \"jvm_threads_daemon\" AND\n  r.service == \"$service\" AND\n  r._field == \"gauge\")\n|> map(fn:(r) => ({\n        _time: r._time,\n        _value: r._value,\n        _measurement: \"daemon\"\n    }))\n|> keep(columns: [\"_value\", \"_time\", \"_measurement\"])"
      },
      {
       "alias": "$tag_state",
       "expr": "jvm_threads_live{service=\"$service\"} - jvm_threads_daemon{service=\"$service\"}",
       "groupBy": [
        { "params": [ "15s" ], "type": "time" },
        { "params": [ "state" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "non-deamon",
       "measurement": "jvm_threads_states",
       "query": "lnd = () => {\nlive = from(bucket: \"telegraf\")\n|> range($range)\n|> filter(fn: (r) =>\n  r._measurement == \"jvm_threads_live\" AND\n  r.service == \"$service\" AND\n  r._field == \"gauge\")\n|> keep(columns: [\"_value\", \"_time\", \"_measurement\"])\n  \ndaemon = from(bucket: \"telegraf\")\n|> range($range)\n|> filter(fn: (r) =>\n  r._measurement == \"jvm_threads_daemon\" AND\n  r.service == \"$service\" AND\n  r._field == \"gauge\")\n|> keep(columns: [\"_value\", \"_time\", \"_measurement\"])\n  \nreturn join(tables:{live:live, daemon:daemon},on:[\"_time\",\"_stop\",\"_start\", \"host\"])\n    |> map(fn:(r) => ({\n        _time: r._time,\n        _value: (r._value_live - r._value_daemon),\n        _measurement: \"non-daemon\"\n    }))\n}\n\nlnd()",
       "select": [
        [
         { "params": [ "gauge" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "service", "operator": "=~", "value": "/^$service$/" }
       ]
      },
      {
       "expr": "jvm_threads_peak{service=\"$service\"} - jvm_threads_live{service=\"$service\"}",
       "legendFormat": "peak",
       "query": "stackedPeak = () => {\npeak = from(bucket: \"telegraf\")\n|> range($range)\n|> filter(fn: (r) =>\n  r._measurement == \"jvm_threads_peak\" AND\n  r.service == \"$service\" AND\n  r._field == \"gauge\")\n|> keep(columns: [\"_value\", \"_time\", \"_measurement\"])\n\nlive = from(bucket: \"telegraf\")\n|> range($range)\n|> filter(fn: (r) =>\n  r._measurement == \"jvm_threads_live\" AND\n  r.service == \"$service\" AND\n  r._field == \"gauge\")\n|> keep(columns: [\"_value\", \"_time\", \"_measurement\"])\n  \n\n  \nreturn join(tables:{live:live, peak:peak},on:[\"_time\",\"_stop\",\"_start\", \"host\"])\n    |> map(fn:(r) => ({\n        _time: r._time,\n        _value: (r._value_peak - r._value_live),\n        _measurement: \"peak\"\n    }))\n}\n\nstackedPeak()"
      }
     ]
    },
    {
     "title": "Garbage Collection Memory",
     "type": "graph",
     "gridPos": { "h": 6, "w": 5, "x": 19, "y": 17 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "Live Data Size",
       "expr": "jvm_gc_live_data_size{service=\"$service\"}",
       "groupBy": [
        { "params": [ "15s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Live Data Size",
       "measurement": "jvm_gc_live_data_size",
       "query": "SELECT \"gauge\" FROM \"jvm_gc_live_data_size\" WHERE (\"service\" =~ /^$service$/) ",
       "select": [
        [
         { "params": [ "gauge" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "service", "operator": "=~", "value": "/^$service$/" }
       ]
      },
      {
       "alias": "Max Data Size",
       "expr": "jvm_gc_max_data_size{service=\"$service\"}",
       "groupBy": [
        { "params": [ "15s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Max Data Size",
       "measurement": "jvm_gc_max_data_size",
       "query": "SELECT \"gauge\" FROM \"jvm_gc_live_data_size\" WHERE (\"service\" =~ /^$service$/) ",
       "select": [
        [
         { "params": [ "gauge" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "service", "operator": "=~", "value": "/^$service$/" }
       ]
      },
      {
       "alias": "Allocated Memory",
       "expr": "idelta(jvm_gc_memory_allocated{service=\"$service\"}[$__range])",
       "groupBy": [
        { "params": [ "15s" ], "type": "time" }
       ],
       "legendFormat": "Allocated Memory",
       "measurement": "jvm_gc_memory_allocated",
       "query": "SELECT difference(sum(\"counter\")) FROM \"jvm_gc_memory_allocated\" WHERE (\"service\" =~ /^$service$/) AND $timeFilter GROUP BY time(15s)",
       "select": [
        [
         { "params": [ "counter" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         {
          "params": [],
          "type": "non_negative_difference"
         }
        ]
       ],
       "tags": [
        { "key": "service", "operator": "=~", "value": "/^$service$/" }
       ]
      },
      {
       "alias": "Promoted Memory",
       "expr": "idelta(jvm_gc_memory_promoted{service=\"$service\"}[$__range])",
       "groupBy": [
        { "params": [ "15s" ], "type": "time" }
       ],
       "legendFormat": "Promoted Memory",
       "measurement": "jvm_gc_memory_promoted",
       "query": "SELECT difference(sum(\"counter\")) FROM \"jvm_gc_memory_allocated\" WHERE (\"service\" =~ /^$service$/) AND $timeFilter GROUP BY time(15s)",
       "select": [
        [
         { "params": [ "counter" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         {
          "params": [],
          "type": "non_negative_difference"
         }
        ]
       ],
       "tags": [
        { "key": "service", "operator": "=~", "value": "/^$service$/" }
       ]
      }
     ]
    },
    {
     "title": "Current CPU Usage",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 23 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "expr": "process_cpu_usage{service=\"$service\"}",
       "measurement": "process_cpu_usage",
       "select": [
        [
         { "params": [ "gauge" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "service", "operator": "=~", "value": "/^$service$/" }
       ]
      }
     ]
    },
    {
     "title": "Loaded Classes",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 4, "y": 23 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "jvm_classes_loaded{service=\"$service\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "from(bucket: \"telegraf\")\n  |> range(start: -1m)\n  |> filter(fn: (r) =>\n    r._measurement == \"jvm_classes_loaded\" AND\n    r.service == \"$service\" AND\n    r._field == \"gauge\")\n  |> keep(columns: [\"_value\", \"_time\", \"service\"])\n  |> last()\n",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Memory - Non-Heap",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 7, "y": 23 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "max",
       "expr": "sum(jvm_memory_max{service=\"$service\", area=\"nonheap\"})",
       "groupBy": [
        { "params": [ "15s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "max",
       "measurement": "jvm_memory_max",
       "query": "SELECT mean(\"gauge\") FROM \"jvm_memory_max\" WHERE (\"service\" =~ /^$service$/) AND $timeFilter GROUP BY time(1m) fill(null)",
       "select": [
        [
         { "params": [ "gauge" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "service", "operator": "=~", "value": "/^$service$/" },
        { "condition": "AND", "key": "area", "operator": "=", "value": "nonheap" }
       ]
      },
      {
       "alias": "committed",
       "expr": "sum(jvm_memory_committed{service=\"$service\", area=\"nonheap\"})",
       "groupBy": [
        { "params": [ "15s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "committed",
       "measurement": "jvm_memory_committed",
       "query": "SELECT mean(\"gauge\") FROM \"jvm_memory_max\" WHERE (\"service\" =~ /^$service$/) AND $timeFilter GROUP BY time(1m) fill(null)",
       "select": [
        [
         { "params": [ "gauge" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "service", "operator": "=~", "value": "/^$service$/" },
        { "condition": "AND", "key": "area", "operator": "=", "value": "nonheap" }
       ]
      },
      {
       "alias": "used",
       "expr": "sum(jvm_memory_used{service=\"$service\", area=\"nonheap\"})",
       "groupBy": [
        { "params": [ "15s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "used",
       "measurement": "jvm_memory_used",
       "query": "SELECT mean(\"gauge\") FROM \"jvm_memory_max\" WHERE (\"service\" =~ /^$service$/) AND $timeFilter GROUP BY time(1m) fill(null)",
       "select": [
        [
         { "params": [ "gauge" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "service", "operator": "=~", "value": "/^$service$/" },
        { "condition": "AND", "key": "area", "operator": "=", "value": "nonheap" }
       ]
      }
     ]
    },
    {
     "title": "# Threads by States",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 13, "y": 23 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "$tag_state",
       "expr": "jvm_threads_states{service=\"$service\"}",
       "groupBy": [
        { "params": [ "15s" ], "type": "time" },
        { "params": [ "state" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{state}}",
       "measurement": "jvm_threads_states",
       "query": "SELECT mean(\"gauge\") FROM \"jvm_memory_max\" WHERE (\"service\" =~ /^$service$/) AND $timeFilter GROUP BY time(1m) fill(null)",
       "select": [
        [
         { "params": [ "gauge" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "service", "operator": "=~", "value": "/^$service$/" }
       ]
      }
     ]
    },
    {
     "title": "Garbage Collection Pauses",
     "type": "graph",
     "gridPos": { "h": 6, "w": 5, "x": 19, "y": 23 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "sum(idelta(jvm_gc_pause{service=\"$service\", action=\"end of minor GC\"}[$__range]))",
       "legendFormat": "Minor GC"
      },
      {
       "expr": "idelta(jvm_gc_pause{service=\"$service\", action=\"end of major GC\"}[$__range])",
       "legendFormat": "Major GC"
      }
     ]
    },
    {
     "title": "Unloaded Classes",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 4, "y": 26 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "jvm_classes_unloaded{service=\"$service\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "from(bucket: \"telegraf\")\n  |> range(start: -1m)\n  |> filter(fn: (r) =>\n    r._measurement == \"jvm_classes_unloaded\" AND\n    r.service == \"$service\" AND\n    r._field == \"gauge\")\n  |> keep(columns: [\"_value\", \"_time\", \"service\"])\n  |> last()\n",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    { "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 }, "content": "----" }
   ]
  },
  {
   "title": "$service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "graph",
     "gridPos": { "h": 6, "w": 7, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "process_cpu_usage{service=\"$service\"}",
       "legendFormat": "process_cpu_usage",
       "query": "from(bucket: \"telegraf\")\n|> range($range)\n|> filter(fn: (r) =>\n  r._measurement == \"process_cpu_usage\" AND\n  r.service == \"$service\" AND\n  r._field == \"gauge\")\n|> keep(columns: [\"_value\", \"_time\", \"_measurement\"])"
      },
      {
       "expr": "system_cpu_usage{service=\"$service\"}",
       "legendFormat": "system_cpu_usage",
       "query": "from(bucket: \"telegraf\")\n|> range($range)\n|> filter(fn: (r) =>\n  r._measurement == \"system_cpu_usage\" AND\n  r.service == \"$service\" AND\n  r._field == \"gauge\")\n|> keep(columns: [\"_value\", \"_time\", \"_measurement\"])\n"
      }
     ]
    },
    {
     "title": "Memory - Heap",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 7, "y": 5 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "max",
       "expr": "sum(jvm_memory_max{service=\"$service\", area=\"heap\"})",
       "groupBy": [
        { "params": [ "15s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "max",
       "measurement": "jvm_memory_max",
       "query": "SELECT mean(\"gauge\") FROM \"jvm_memory_max\" WHERE (\"service\" =~ /^$service$/) AND $timeFilter GROUP BY time(1m) fill(null)",
       "select": [
        [
         { "params": [ "gauge" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "service", "operator": "=~", "value": "/^$service$/" },
        { "condition": "AND", "key": "area", "operator": "=", "value": "heap" }
       ]
      },
      {
       "alias": "committed",
       "expr": "sum(jvm_memory_committed{service=\"$service\", area=\"heap\"})",
       "groupBy": [
        { "params": [ "15s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "committed",
       "measurement": "jvm_memory_committed",
       "query": "SELECT mean(\"gauge\") FROM \"jvm_memory_max\" WHERE (\"service\" =~ /^$service$/) AND $timeFilter GROUP BY time(1m) fill(null)",
       "select": [
        [
         { "params": [ "gauge" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "service", "operator": "=~", "value": "/^$service$/" },
        { "condition": "AND", "key": "area", "operator": "=", "value": "heap" }
       ]
      },
      {
       "alias": "used",
       "expr": "sum(jvm_memory_used{service=\"$service\", area=\"heap\"})",
       "groupBy": [
        { "params": [ "15s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "used",
       "measurement": "jvm_memory_used",
       "query": "SELECT mean(\"gauge\") FROM \"jvm_memory_max\" WHERE (\"service\" =~ /^$service$/) AND $timeFilter GROUP BY time(1m) fill(null)",
       "select": [
        [
         { "params": [ "gauge" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "service", "operator": "=~", "value": "/^$service$/" },
        { "condition": "AND", "key": "area", "operator": "=", "value": "heap" }
       ]
      }
     ]
    },
    {
     "title": "# Live Threads",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 13, "y": 5 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "jvm_threads_daemon{service=\"$service\"}",
       "legendFormat": "daemon",
       "query": "from(bucket: \"telegraf\")\n|> range($range)\n|> filter(fn: (r) =>\n  r._measurement == \"jvm_threads_daemon\" AND\n  r.service == \"$service\" AND\n  r._field == \"gauge\")\n|> map(fn:(r) => ({\n        _time: r._time,\n        _value: r._value,\n        _measurement: \"daemon\"\n    }))\n|> keep(columns: [\"_value\", \"_time\", \"_measurement\"])"
      },
      {
       "alias": "$tag_state",
       "expr": "jvm_threads_live{service=\"$service\"} - jvm_threads_daemon{service=\"$service\"}",
       "groupBy": [
        { "params": [ "15s" ], "type": "time" },
        { "params": [ "state" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "non-deamon",
       "measurement": "jvm_threads_states",
       "query": "lnd = () => {\nlive = from(bucket: \"telegraf\")\n|> range($range)\n|> filter(fn: (r) =>\n  r._measurement == \"jvm_threads_live\" AND\n  r.service == \"$service\" AND\n  r._field == \"gauge\")\n|> keep(columns: [\"_value\", \"_time\", \"_measurement\"])\n  \ndaemon = from(bucket: \"telegraf\")\n|> range($range)\n|> filter(fn: (r) =>\n  r._measurement == \"jvm_threads_daemon\" AND\n  r.service == \"$service\" AND\n  r._field == \"gauge\")\n|> keep(columns: [\"_value\", \"_time\", \"_measurement\"])\n  \nreturn join(tables:{live:live, daemon:daemon},on:[\"_time\",\"_stop\",\"_start\", \"host\"])\n    |> map(fn:(r) => ({\n        _time: r._time,\n        _value: (r._value_live - r._value_daemon),\n        _measurement: \"non-daemon\"\n    }))\n}\n\nlnd()",
       "select": [
        [
         { "params": [ "gauge" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "service", "operator": "=~", "value": "/^$service$/" }
       ]
      },
      {
       "expr": "jvm_threads_peak{service=\"$service\"} - jvm_threads_live{service=\"$service\"}",
       "legendFormat": "peak",
       "query": "stackedPeak = () => {\npeak = from(bucket: \"telegraf\")\n|> range($range)\n|> filter(fn: (r) =>\n  r._measurement == \"jvm_threads_peak\" AND\n  r.service == \"$service\" AND\n  r._field == \"gauge\")\n|> keep(columns: [\"_value\", \"_time\", \"_measurement\"])\n\nlive = from(bucket: \"telegraf\")\n|> range($range)\n|> filter(fn: (r) =>\n  r._measurement == \"jvm_threads_live\" AND\n  r.service == \"$service\" AND\n  r._field == \"gauge\")\n|> keep(columns: [\"_value\", \"_time\", \"_measurement\"])\n  \n\n  \nreturn join(tables:{live:live, peak:peak},on:[\"_time\",\"_stop\",\"_start\", \"host\"])\n    |> map(fn:(r) => ({\n        _time: r._time,\n        _value: (r._value_peak - r._value_live),\n        _measurement: \"peak\"\n    }))\n}\n\nstackedPeak()"
      }
     ]
    },
    {
     "title": "Garbage Collection Memory",
     "type": "graph",
     "gridPos": { "h": 6, "w": 5, "x": 19, "y": 5 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "Live Data Size",
       "expr": "jvm_gc_live_data_size{service=\"$service\"}",
       "groupBy": [
        { "params": [ "15s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Live Data Size",
       "measurement": "jvm_gc_live_data_size",
       "query": "SELECT \"gauge\" FROM \"jvm_gc_live_data_size\" WHERE (\"service\" =~ /^$service$/) ",
       "select": [
        [
         { "params": [ "gauge" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "service", "operator": "=~", "value": "/^$service$/" }
       ]
      },
      {
       "alias": "Max Data Size",
       "expr": "jvm_gc_max_data_size{service=\"$service\"}",
       "groupBy": [
        { "params": [ "15s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Max Data Size",
       "measurement": "jvm_gc_max_data_size",
       "query": "SELECT \"gauge\" FROM \"jvm_gc_live_data_size\" WHERE (\"service\" =~ /^$service$/) ",
       "select": [
        [
         { "params": [ "gauge" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "service", "operator": "=~", "value": "/^$service$/" }
       ]
      },
      {
       "alias": "Allocated Memory",
       "expr": "idelta(jvm_gc_memory_allocated{service=\"$service\"}[$__range])",
       "groupBy": [
        { "params": [ "15s" ], "type": "time" }
       ],
       "legendFormat": "Allocated Memory",
       "measurement": "jvm_gc_memory_allocated",
       "query": "SELECT difference(sum(\"counter\")) FROM \"jvm_gc_memory_allocated\" WHERE (\"service\" =~ /^$service$/) AND $timeFilter GROUP BY time(15s)",
       "select": [
        [
         { "params": [ "counter" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         {
          "params": [],
          "type": "non_negative_difference"
         }
        ]
       ],
       "tags": [
        { "key": "service", "operator": "=~", "value": "/^$service$/" }
       ]
      },
      {
       "alias": "Promoted Memory",
       "expr": "idelta(jvm_gc_memory_promoted{service=\"$service\"}[$__range])",
       "groupBy": [
        { "params": [ "15s" ], "type": "time" }
       ],
       "legendFormat": "Promoted Memory",
       "measurement": "jvm_gc_memory_promoted",
       "query": "SELECT difference(sum(\"counter\")) FROM \"jvm_gc_memory_allocated\" WHERE (\"service\" =~ /^$service$/) AND $timeFilter GROUP BY time(15s)",
       "select": [
        [
         { "params": [ "counter" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         {
          "params": [],
          "type": "non_negative_difference"
         }
        ]
       ],
       "tags": [
        { "key": "service", "operator": "=~", "value": "/^$service$/" }
       ]
      }
     ]
    },
    {
     "title": "Current CPU Usage",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 11 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "expr": "process_cpu_usage{service=\"$service\"}",
       "measurement": "process_cpu_usage",
       "select": [
        [
         { "params": [ "gauge" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "service", "operator": "=~", "value": "/^$service$/" }
       ]
      }
     ]
    },
    {
     "title": "Loaded Classes",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 4, "y": 11 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "jvm_classes_loaded{service=\"$service\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "from(bucket: \"telegraf\")\n  |> range(start: -1m)\n  |> filter(fn: (r) =>\n    r._measurement == \"jvm_classes_loaded\" AND\n    r.service == \"$service\" AND\n    r._field == \"gauge\")\n  |> keep(columns: [\"_value\", \"_time\", \"service\"])\n  |> last()\n",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Memory - Non-Heap",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 7, "y": 11 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "max",
       "expr": "sum(jvm_memory_max{service=\"$service\", area=\"nonheap\"})",
       "groupBy": [
        { "params": [ "15s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "max",
       "measurement": "jvm_memory_max",
       "query": "SELECT mean(\"gauge\") FROM \"jvm_memory_max\" WHERE (\"service\" =~ /^$service$/) AND $timeFilter GROUP BY time(1m) fill(null)",
       "select": [
        [
         { "params": [ "gauge" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "service", "operator": "=~", "value": "/^$service$/" },
        { "condition": "AND", "key": "area", "operator": "=", "value": "nonheap" }
       ]
      },
      {
       "alias": "committed",
       "expr": "sum(jvm_memory_committed{service=\"$service\", area=\"nonheap\"})",
       "groupBy": [
        { "params": [ "15s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "committed",
       "measurement": "jvm_memory_committed",
       "query": "SELECT mean(\"gauge\") FROM \"jvm_memory_max\" WHERE (\"service\" =~ /^$service$/) AND $timeFilter GROUP BY time(1m) fill(null)",
       "select": [
        [
         { "params": [ "gauge" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "service", "operator": "=~", "value": "/^$service$/" },
        { "condition": "AND", "key": "area", "operator": "=", "value": "nonheap" }
       ]
      },
      {
       "alias": "used",
       "expr": "sum(jvm_memory_used{service=\"$service\", area=\"nonheap\"})",
       "groupBy": [
        { "params": [ "15s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "used",
       "measurement": "jvm_memory_used",
       "query": "SELECT mean(\"gauge\") FROM \"jvm_memory_max\" WHERE (\"service\" =~ /^$service$/) AND $timeFilter GROUP BY time(1m) fill(null)",
       "select": [
        [
         { "params": [ "gauge" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "service", "operator": "=~", "value": "/^$service$/" },
        { "condition": "AND", "key": "area", "operator": "=", "value": "nonheap" }
       ]
      }
     ]
    },
    {
     "title": "# Threads by States",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 13, "y": 11 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "$tag_state",
       "expr": "jvm_threads_states{service=\"$service\"}",
       "groupBy": [
        { "params": [ "15s" ], "type": "time" },
        { "params": [ "state" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{state}}",
       "measurement": "jvm_threads_states",
       "query": "SELECT mean(\"gauge\") FROM \"jvm_memory_max\" WHERE (\"service\" =~ /^$service$/) AND $timeFilter GROUP BY time(1m) fill(null)",
       "select": [
        [
         { "params": [ "gauge" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "service", "operator": "=~", "value": "/^$service$/" }
       ]
      }
     ]
    },
    {
     "title": "Garbage Collection Pauses",
     "type": "graph",
     "gridPos": { "h": 6, "w": 5, "x": 19, "y": 11 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "sum(idelta(jvm_gc_pause{service=\"$service\", action=\"end of minor GC\"}[$__range]))",
       "legendFormat": "Minor GC"
      },
      {
       "expr": "idelta(jvm_gc_pause{service=\"$service\", action=\"end of major GC\"}[$__range])",
       "legendFormat": "Major GC"
      }
     ]
    },
    {
     "title": "Unloaded Classes",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 4, "y": 14 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "jvm_classes_unloaded{service=\"$service\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "from(bucket: \"telegraf\")\n  |> range(start: -1m)\n  |> filter(fn: (r) =>\n    r._measurement == \"jvm_classes_unloaded\" AND\n    r.service == \"$service\" AND\n    r._field == \"gauge\")\n  |> keep(columns: [\"_value\", \"_time\", \"service\"])\n  |> last()\n",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    { "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 }, "content": "----" }
   ]
  },
  {
   "title": "$service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "graph",
     "gridPos": { "h": 6, "w": 7, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "process_cpu_usage{service=\"$service\"}",
       "legendFormat": "process_cpu_usage",
       "query": "from(bucket: \"telegraf\")\n|> range($range)\n|> filter(fn: (r) =>\n  r._measurement == \"process_cpu_usage\" AND\n  r.service == \"$service\" AND\n  r._field == \"gauge\")\n|> keep(columns: [\"_value\", \"_time\", \"_measurement\"])"
      },
      {
       "expr": "system_cpu_usage{service=\"$service\"}",
       "legendFormat": "system_cpu_usage",
       "query": "from(bucket: \"telegraf\")\n|> range($range)\n|> filter(fn: (r) =>\n  r._measurement == \"system_cpu_usage\" AND\n  r.service == \"$service\" AND\n  r._field == \"gauge\")\n|> keep(columns: [\"_value\", \"_time\", \"_measurement\"])\n"
      }
     ]
    },
    {
     "title": "Memory - Heap",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 7, "y": 6 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "max",
       "expr": "sum(jvm_memory_max{service=\"$service\", area=\"heap\"})",
       "groupBy": [
        { "params": [ "15s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "max",
       "measurement": "jvm_memory_max",
       "query": "SELECT mean(\"gauge\") FROM \"jvm_memory_max\" WHERE (\"service\" =~ /^$service$/) AND $timeFilter GROUP BY time(1m) fill(null)",
       "select": [
        [
         { "params": [ "gauge" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "service", "operator": "=~", "value": "/^$service$/" },
        { "condition": "AND", "key": "area", "operator": "=", "value": "heap" }
       ]
      },
      {
       "alias": "committed",
       "expr": "sum(jvm_memory_committed{service=\"$service\", area=\"heap\"})",
       "groupBy": [
        { "params": [ "15s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "committed",
       "measurement": "jvm_memory_committed",
       "query": "SELECT mean(\"gauge\") FROM \"jvm_memory_max\" WHERE (\"service\" =~ /^$service$/) AND $timeFilter GROUP BY time(1m) fill(null)",
       "select": [
        [
         { "params": [ "gauge" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "service", "operator": "=~", "value": "/^$service$/" },
        { "condition": "AND", "key": "area", "operator": "=", "value": "heap" }
       ]
      },
      {
       "alias": "used",
       "expr": "sum(jvm_memory_used{service=\"$service\", area=\"heap\"})",
       "groupBy": [
        { "params": [ "15s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "used",
       "measurement": "jvm_memory_used",
       "query": "SELECT mean(\"gauge\") FROM \"jvm_memory_max\" WHERE (\"service\" =~ /^$service$/) AND $timeFilter GROUP BY time(1m) fill(null)",
       "select": [
        [
         { "params": [ "gauge" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "service", "operator": "=~", "value": "/^$service$/" },
        { "condition": "AND", "key": "area", "operator": "=", "value": "heap" }
       ]
      }
     ]
    },
    {
     "title": "# Live Threads",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 13, "y": 6 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "jvm_threads_daemon{service=\"$service\"}",
       "legendFormat": "daemon",
       "query": "from(bucket: \"telegraf\")\n|> range($range)\n|> filter(fn: (r) =>\n  r._measurement == \"jvm_threads_daemon\" AND\n  r.service == \"$service\" AND\n  r._field == \"gauge\")\n|> map(fn:(r) => ({\n        _time: r._time,\n        _value: r._value,\n        _measurement: \"daemon\"\n    }))\n|> keep(columns: [\"_value\", \"_time\", \"_measurement\"])"
      },
      {
       "alias": "$tag_state",
       "expr": "jvm_threads_live{service=\"$service\"} - jvm_threads_daemon{service=\"$service\"}",
       "groupBy": [
        { "params": [ "15s" ], "type": "time" },
        { "params": [ "state" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "non-deamon",
       "measurement": "jvm_threads_states",
       "query": "lnd = () => {\nlive = from(bucket: \"telegraf\")\n|> range($range)\n|> filter(fn: (r) =>\n  r._measurement == \"jvm_threads_live\" AND\n  r.service == \"$service\" AND\n  r._field == \"gauge\")\n|> keep(columns: [\"_value\", \"_time\", \"_measurement\"])\n  \ndaemon = from(bucket: \"telegraf\")\n|> range($range)\n|> filter(fn: (r) =>\n  r._measurement == \"jvm_threads_daemon\" AND\n  r.service == \"$service\" AND\n  r._field == \"gauge\")\n|> keep(columns: [\"_value\", \"_time\", \"_measurement\"])\n  \nreturn join(tables:{live:live, daemon:daemon},on:[\"_time\",\"_stop\",\"_start\", \"host\"])\n    |> map(fn:(r) => ({\n        _time: r._time,\n        _value: (r._value_live - r._value_daemon),\n        _measurement: \"non-daemon\"\n    }))\n}\n\nlnd()",
       "select": [
        [
         { "params": [ "gauge" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "service", "operator": "=~", "value": "/^$service$/" }
       ]
      },
      {
       "expr": "jvm_threads_peak{service=\"$service\"} - jvm_threads_live{service=\"$service\"}",
       "legendFormat": "peak",
       "query": "stackedPeak = () => {\npeak = from(bucket: \"telegraf\")\n|> range($range)\n|> filter(fn: (r) =>\n  r._measurement == \"jvm_threads_peak\" AND\n  r.service == \"$service\" AND\n  r._field == \"gauge\")\n|> keep(columns: [\"_value\", \"_time\", \"_measurement\"])\n\nlive = from(bucket: \"telegraf\")\n|> range($range)\n|> filter(fn: (r) =>\n  r._measurement == \"jvm_threads_live\" AND\n  r.service == \"$service\" AND\n  r._field == \"gauge\")\n|> keep(columns: [\"_value\", \"_time\", \"_measurement\"])\n  \n\n  \nreturn join(tables:{live:live, peak:peak},on:[\"_time\",\"_stop\",\"_start\", \"host\"])\n    |> map(fn:(r) => ({\n        _time: r._time,\n        _value: (r._value_peak - r._value_live),\n        _measurement: \"peak\"\n    }))\n}\n\nstackedPeak()"
      }
     ]
    },
    {
     "title": "Garbage Collection Memory",
     "type": "graph",
     "gridPos": { "h": 6, "w": 5, "x": 19, "y": 6 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "Live Data Size",
       "expr": "jvm_gc_live_data_size{service=\"$service\"}",
       "groupBy": [
        { "params": [ "15s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Live Data Size",
       "measurement": "jvm_gc_live_data_size",
       "query": "SELECT \"gauge\" FROM \"jvm_gc_live_data_size\" WHERE (\"service\" =~ /^$service$/) ",
       "select": [
        [
         { "params": [ "gauge" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "service", "operator": "=~", "value": "/^$service$/" }
       ]
      },
      {
       "alias": "Max Data Size",
       "expr": "jvm_gc_max_data_size{service=\"$service\"}",
       "groupBy": [
        { "params": [ "15s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Max Data Size",
       "measurement": "jvm_gc_max_data_size",
       "query": "SELECT \"gauge\" FROM \"jvm_gc_live_data_size\" WHERE (\"service\" =~ /^$service$/) ",
       "select": [
        [
         { "params": [ "gauge" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "service", "operator": "=~", "value": "/^$service$/" }
       ]
      },
      {
       "alias": "Allocated Memory",
       "expr": "idelta(jvm_gc_memory_allocated{service=\"$service\"}[$__range])",
       "groupBy": [
        { "params": [ "15s" ], "type": "time" }
       ],
       "legendFormat": "Allocated Memory",
       "measurement": "jvm_gc_memory_allocated",
       "query": "SELECT difference(sum(\"counter\")) FROM \"jvm_gc_memory_allocated\" WHERE (\"service\" =~ /^$service$/) AND $timeFilter GROUP BY time(15s)",
       "select": [
        [
         { "params": [ "counter" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         {
          "params": [],
          "type": "non_negative_difference"
         }
        ]
       ],
       "tags": [
        { "key": "service", "operator": "=~", "value": "/^$service$/" }
       ]
      },
      {
       "alias": "Promoted Memory",
       "expr": "idelta(jvm_gc_memory_promoted{service=\"$service\"}[$__range])",
       "groupBy": [
        { "params": [ "15s" ], "type": "time" }
       ],
       "legendFormat": "Promoted Memory",
       "measurement": "jvm_gc_memory_promoted",
       "query": "SELECT difference(sum(\"counter\")) FROM \"jvm_gc_memory_allocated\" WHERE (\"service\" =~ /^$service$/) AND $timeFilter GROUP BY time(15s)",
       "select": [
        [
         { "params": [ "counter" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         {
          "params": [],
          "type": "non_negative_difference"
         }
        ]
       ],
       "tags": [
        { "key": "service", "operator": "=~", "value": "/^$service$/" }
       ]
      }
     ]
    },
    {
     "title": "Current CPU Usage",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 12 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "expr": "process_cpu_usage{service=\"$service\"}",
       "measurement": "process_cpu_usage",
       "select": [
        [
         { "params": [ "gauge" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "service", "operator": "=~", "value": "/^$service$/" }
       ]
      }
     ]
    },
    {
     "title": "Loaded Classes",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 4, "y": 12 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "jvm_classes_loaded{service=\"$service\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "from(bucket: \"telegraf\")\n  |> range(start: -1m)\n  |> filter(fn: (r) =>\n    r._measurement == \"jvm_classes_loaded\" AND\n    r.service == \"$service\" AND\n    r._field == \"gauge\")\n  |> keep(columns: [\"_value\", \"_time\", \"service\"])\n  |> last()\n",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Memory - Non-Heap",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 7, "y": 12 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "max",
       "expr": "sum(jvm_memory_max{service=\"$service\", area=\"nonheap\"})",
       "groupBy": [
        { "params": [ "15s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "max",
       "measurement": "jvm_memory_max",
       "query": "SELECT mean(\"gauge\") FROM \"jvm_memory_max\" WHERE (\"service\" =~ /^$service$/) AND $timeFilter GROUP BY time(1m) fill(null)",
       "select": [
        [
         { "params": [ "gauge" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "service", "operator": "=~", "value": "/^$service$/" },
        { "condition": "AND", "key": "area", "operator": "=", "value": "nonheap" }
       ]
      },
      {
       "alias": "committed",
       "expr": "sum(jvm_memory_committed{service=\"$service\", area=\"nonheap\"})",
       "groupBy": [
        { "params": [ "15s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "committed",
       "measurement": "jvm_memory_committed",
       "query": "SELECT mean(\"gauge\") FROM \"jvm_memory_max\" WHERE (\"service\" =~ /^$service$/) AND $timeFilter GROUP BY time(1m) fill(null)",
       "select": [
        [
         { "params": [ "gauge" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "service", "operator": "=~", "value": "/^$service$/" },
        { "condition": "AND", "key": "area", "operator": "=", "value": "nonheap" }
       ]
      },
      {
       "alias": "used",
       "expr": "sum(jvm_memory_used{service=\"$service\", area=\"nonheap\"})",
       "groupBy": [
        { "params": [ "15s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "used",
       "measurement": "jvm_memory_used",
       "query": "SELECT mean(\"gauge\") FROM \"jvm_memory_max\" WHERE (\"service\" =~ /^$service$/) AND $timeFilter GROUP BY time(1m) fill(null)",
       "select": [
        [
         { "params": [ "gauge" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "service", "operator": "=~", "value": "/^$service$/" },
        { "condition": "AND", "key": "area", "operator": "=", "value": "nonheap" }
       ]
      }
     ]
    },
    {
     "title": "# Threads by States",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 13, "y": 12 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "$tag_state",
       "expr": "jvm_threads_states{service=\"$service\"}",
       "groupBy": [
        { "params": [ "15s" ], "type": "time" },
        { "params": [ "state" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{state}}",
       "measurement": "jvm_threads_states",
       "query": "SELECT mean(\"gauge\") FROM \"jvm_memory_max\" WHERE (\"service\" =~ /^$service$/) AND $timeFilter GROUP BY time(1m) fill(null)",
       "select": [
        [
         { "params": [ "gauge" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "service", "operator": "=~", "value": "/^$service$/" }
       ]
      }
     ]
    },
    {
     "title": "Garbage Collection Pauses",
     "type": "graph",
     "gridPos": { "h": 6, "w": 5, "x": 19, "y": 12 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "sum(idelta(jvm_gc_pause{service=\"$service\", action=\"end of minor GC\"}[$__range]))",
       "legendFormat": "Minor GC"
      },
      {
       "expr": "idelta(jvm_gc_pause{service=\"$service\", action=\"end of major GC\"}[$__range])",
       "legendFormat": "Major GC"
      }
     ]
    },
    {
     "title": "Unloaded Classes",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 4, "y": 15 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "jvm_classes_unloaded{service=\"$service\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "from(bucket: \"telegraf\")\n  |> range(start: -1m)\n  |> filter(fn: (r) =>\n    r._measurement == \"jvm_classes_unloaded\" AND\n    r.service == \"$service\" AND\n    r._field == \"gauge\")\n  |> keep(columns: [\"_value\", \"_time\", \"service\"])\n  |> last()\n",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    { "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 }, "content": "----" }
   ]
  },
  {
   "title": "$service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "graph",
     "gridPos": { "h": 6, "w": 7, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "process_cpu_usage{service=\"$service\"}",
       "legendFormat": "process_cpu_usage",
       "query": "from(bucket: \"telegraf\")\n|> range($range)\n|> filter(fn: (r) =>\n  r._measurement == \"process_cpu_usage\" AND\n  r.service == \"$service\" AND\n  r._field == \"gauge\")\n|> keep(columns: [\"_value\", \"_time\", \"_measurement\"])"
      },
      {
       "expr": "system_cpu_usage{service=\"$service\"}",
       "legendFormat": "system_cpu_usage",
       "query": "from(bucket: \"telegraf\")\n|> range($range)\n|> filter(fn: (r) =>\n  r._measurement == \"system_cpu_usage\" AND\n  r.service == \"$service\" AND\n  r._field == \"gauge\")\n|> keep(columns: [\"_value\", \"_time\", \"_measurement\"])\n"
      }
     ]
    },
    {
     "title": "Memory - Heap",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 7, "y": 18 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "max",
       "expr": "sum(jvm_memory_max{service=\"$service\", area=\"heap\"})",
       "groupBy": [
        { "params": [ "15s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "max",
       "measurement": "jvm_memory_max",
       "query": "SELECT mean(\"gauge\") FROM \"jvm_memory_max\" WHERE (\"service\" =~ /^$service$/) AND $timeFilter GROUP BY time(1m) fill(null)",
       "select": [
        [
         { "params": [ "gauge" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "service", "operator": "=~", "value": "/^$service$/" },
        { "condition": "AND", "key": "area", "operator": "=", "value": "heap" }
       ]
      },
      {
       "alias": "committed",
       "expr": "sum(jvm_memory_committed{service=\"$service\", area=\"heap\"})",
       "groupBy": [
        { "params": [ "15s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "committed",
       "measurement": "jvm_memory_committed",
       "query": "SELECT mean(\"gauge\") FROM \"jvm_memory_max\" WHERE (\"service\" =~ /^$service$/) AND $timeFilter GROUP BY time(1m) fill(null)",
       "select": [
        [
         { "params": [ "gauge" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "service", "operator": "=~", "value": "/^$service$/" },
        { "condition": "AND", "key": "area", "operator": "=", "value": "heap" }
       ]
      },
      {
       "alias": "used",
       "expr": "sum(jvm_memory_used{service=\"$service\", area=\"heap\"})",
       "groupBy": [
        { "params": [ "15s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "used",
       "measurement": "jvm_memory_used",
       "query": "SELECT mean(\"gauge\") FROM \"jvm_memory_max\" WHERE (\"service\" =~ /^$service$/) AND $timeFilter GROUP BY time(1m) fill(null)",
       "select": [
        [
         { "params": [ "gauge" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "service", "operator": "=~", "value": "/^$service$/" },
        { "condition": "AND", "key": "area", "operator": "=", "value": "heap" }
       ]
      }
     ]
    },
    {
     "title": "# Live Threads",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 13, "y": 18 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "jvm_threads_daemon{service=\"$service\"}",
       "legendFormat": "daemon",
       "query": "from(bucket: \"telegraf\")\n|> range($range)\n|> filter(fn: (r) =>\n  r._measurement == \"jvm_threads_daemon\" AND\n  r.service == \"$service\" AND\n  r._field == \"gauge\")\n|> map(fn:(r) => ({\n        _time: r._time,\n        _value: r._value,\n        _measurement: \"daemon\"\n    }))\n|> keep(columns: [\"_value\", \"_time\", \"_measurement\"])"
      },
      {
       "alias": "$tag_state",
       "expr": "jvm_threads_live{service=\"$service\"} - jvm_threads_daemon{service=\"$service\"}",
       "groupBy": [
        { "params": [ "15s" ], "type": "time" },
        { "params": [ "state" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "non-deamon",
       "measurement": "jvm_threads_states",
       "query": "lnd = () => {\nlive = from(bucket: \"telegraf\")\n|> range($range)\n|> filter(fn: (r) =>\n  r._measurement == \"jvm_threads_live\" AND\n  r.service == \"$service\" AND\n  r._field == \"gauge\")\n|> keep(columns: [\"_value\", \"_time\", \"_measurement\"])\n  \ndaemon = from(bucket: \"telegraf\")\n|> range($range)\n|> filter(fn: (r) =>\n  r._measurement == \"jvm_threads_daemon\" AND\n  r.service == \"$service\" AND\n  r._field == \"gauge\")\n|> keep(columns: [\"_value\", \"_time\", \"_measurement\"])\n  \nreturn join(tables:{live:live, daemon:daemon},on:[\"_time\",\"_stop\",\"_start\", \"host\"])\n    |> map(fn:(r) => ({\n        _time: r._time,\n        _value: (r._value_live - r._value_daemon),\n        _measurement: \"non-daemon\"\n    }))\n}\n\nlnd()",
       "select": [
        [
         { "params": [ "gauge" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "service", "operator": "=~", "value": "/^$service$/" }
       ]
      },
      {
       "expr": "jvm_threads_peak{service=\"$service\"} - jvm_threads_live{service=\"$service\"}",
       "legendFormat": "peak",
       "query": "stackedPeak = () => {\npeak = from(bucket: \"telegraf\")\n|> range($range)\n|> filter(fn: (r) =>\n  r._measurement == \"jvm_threads_peak\" AND\n  r.service == \"$service\" AND\n  r._field == \"gauge\")\n|> keep(columns: [\"_value\", \"_time\", \"_measurement\"])\n\nlive = from(bucket: \"telegraf\")\n|> range($range)\n|> filter(fn: (r) =>\n  r._measurement == \"jvm_threads_live\" AND\n  r.service == \"$service\" AND\n  r._field == \"gauge\")\n|> keep(columns: [\"_value\", \"_time\", \"_measurement\"])\n  \n\n  \nreturn join(tables:{live:live, peak:peak},on:[\"_time\",\"_stop\",\"_start\", \"host\"])\n    |> map(fn:(r) => ({\n        _time: r._time,\n        _value: (r._value_peak - r._value_live),\n        _measurement: \"peak\"\n    }))\n}\n\nstackedPeak()"
      }
     ]
    },
    {
     "title": "Garbage Collection Memory",
     "type": "graph",
     "gridPos": { "h": 6, "w": 5, "x": 19, "y": 18 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "Live Data Size",
       "expr": "jvm_gc_live_data_size{service=\"$service\"}",
       "groupBy": [
        { "params": [ "15s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Live Data Size",
       "measurement": "jvm_gc_live_data_size",
       "query": "SELECT \"gauge\" FROM \"jvm_gc_live_data_size\" WHERE (\"service\" =~ /^$service$/) ",
       "select": [
        [
         { "params": [ "gauge" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "service", "operator": "=~", "value": "/^$service$/" }
       ]
      },
      {
       "alias": "Max Data Size",
       "expr": "jvm_gc_max_data_size{service=\"$service\"}",
       "groupBy": [
        { "params": [ "15s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Max Data Size",
       "measurement": "jvm_gc_max_data_size",
       "query": "SELECT \"gauge\" FROM \"jvm_gc_live_data_size\" WHERE (\"service\" =~ /^$service$/) ",
       "select": [
        [
         { "params": [ "gauge" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "service", "operator": "=~", "value": "/^$service$/" }
       ]
      },
      {
       "alias": "Allocated Memory",
       "expr": "idelta(jvm_gc_memory_allocated{service=\"$service\"}[$__range])",
       "groupBy": [
        { "params": [ "15s" ], "type": "time" }
       ],
       "legendFormat": "Allocated Memory",
       "measurement": "jvm_gc_memory_allocated",
       "query": "SELECT difference(sum(\"counter\")) FROM \"jvm_gc_memory_allocated\" WHERE (\"service\" =~ /^$service$/) AND $timeFilter GROUP BY time(15s)",
       "select": [
        [
         { "params": [ "counter" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         {
          "params": [],
          "type": "non_negative_difference"
         }
        ]
       ],
       "tags": [
        { "key": "service", "operator": "=~", "value": "/^$service$/" }
       ]
      },
      {
       "alias": "Promoted Memory",
       "expr": "idelta(jvm_gc_memory_promoted{service=\"$service\"}[$__range])",
       "groupBy": [
        { "params": [ "15s" ], "type": "time" }
       ],
       "legendFormat": "Promoted Memory",
       "measurement": "jvm_gc_memory_promoted",
       "query": "SELECT difference(sum(\"counter\")) FROM \"jvm_gc_memory_allocated\" WHERE (\"service\" =~ /^$service$/) AND $timeFilter GROUP BY time(15s)",
       "select": [
        [
         { "params": [ "counter" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         {
          "params": [],
          "type": "non_negative_difference"
         }
        ]
       ],
       "tags": [
        { "key": "service", "operator": "=~", "value": "/^$service$/" }
       ]
      }
     ]
    },
    {
     "title": "Current CPU Usage",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 24 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "expr": "process_cpu_usage{service=\"$service\"}",
       "measurement": "process_cpu_usage",
       "select": [
        [
         { "params": [ "gauge" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "service", "operator": "=~", "value": "/^$service$/" }
       ]
      }
     ]
    },
    {
     "title": "Loaded Classes",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 4, "y": 24 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "jvm_classes_loaded{service=\"$service\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "from(bucket: \"telegraf\")\n  |> range(start: -1m)\n  |> filter(fn: (r) =>\n    r._measurement == \"jvm_classes_loaded\" AND\n    r.service == \"$service\" AND\n    r._field == \"gauge\")\n  |> keep(columns: [\"_value\", \"_time\", \"service\"])\n  |> last()\n",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Memory - Non-Heap",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 7, "y": 24 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "max",
       "expr": "sum(jvm_memory_max{service=\"$service\", area=\"nonheap\"})",
       "groupBy": [
        { "params": [ "15s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "max",
       "measurement": "jvm_memory_max",
       "query": "SELECT mean(\"gauge\") FROM \"jvm_memory_max\" WHERE (\"service\" =~ /^$service$/) AND $timeFilter GROUP BY time(1m) fill(null)",
       "select": [
        [
         { "params": [ "gauge" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "service", "operator": "=~", "value": "/^$service$/" },
        { "condition": "AND", "key": "area", "operator": "=", "value": "nonheap" }
       ]
      },
      {
       "alias": "committed",
       "expr": "sum(jvm_memory_committed{service=\"$service\", area=\"nonheap\"})",
       "groupBy": [
        { "params": [ "15s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "committed",
       "measurement": "jvm_memory_committed",
       "query": "SELECT mean(\"gauge\") FROM \"jvm_memory_max\" WHERE (\"service\" =~ /^$service$/) AND $timeFilter GROUP BY time(1m) fill(null)",
       "select": [
        [
         { "params": [ "gauge" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "service", "operator": "=~", "value": "/^$service$/" },
        { "condition": "AND", "key": "area", "operator": "=", "value": "nonheap" }
       ]
      },
      {
       "alias": "used",
       "expr": "sum(jvm_memory_used{service=\"$service\", area=\"nonheap\"})",
       "groupBy": [
        { "params": [ "15s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "used",
       "measurement": "jvm_memory_used",
       "query": "SELECT mean(\"gauge\") FROM \"jvm_memory_max\" WHERE (\"service\" =~ /^$service$/) AND $timeFilter GROUP BY time(1m) fill(null)",
       "select": [
        [
         { "params": [ "gauge" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "service", "operator": "=~", "value": "/^$service$/" },
        { "condition": "AND", "key": "area", "operator": "=", "value": "nonheap" }
       ]
      }
     ]
    },
    {
     "title": "# Threads by States",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 13, "y": 24 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "$tag_state",
       "expr": "jvm_threads_states{service=\"$service\"}",
       "groupBy": [
        { "params": [ "15s" ], "type": "time" },
        { "params": [ "state" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{state}}",
       "measurement": "jvm_threads_states",
       "query": "SELECT mean(\"gauge\") FROM \"jvm_memory_max\" WHERE (\"service\" =~ /^$service$/) AND $timeFilter GROUP BY time(1m) fill(null)",
       "select": [
        [
         { "params": [ "gauge" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "service", "operator": "=~", "value": "/^$service$/" }
       ]
      }
     ]
    },
    {
     "title": "Garbage Collection Pauses",
     "type": "graph",
     "gridPos": { "h": 6, "w": 5, "x": 19, "y": 24 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "sum(idelta(jvm_gc_pause{service=\"$service\", action=\"end of minor GC\"}[$__range]))",
       "legendFormat": "Minor GC"
      },
      {
       "expr": "idelta(jvm_gc_pause{service=\"$service\", action=\"end of major GC\"}[$__range])",
       "legendFormat": "Major GC"
      }
     ]
    },
    {
     "title": "Unloaded Classes",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 4, "y": 27 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "jvm_classes_unloaded{service=\"$service\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "from(bucket: \"telegraf\")\n  |> range(start: -1m)\n  |> filter(fn: (r) =>\n    r._measurement == \"jvm_classes_unloaded\" AND\n    r.service == \"$service\" AND\n    r._field == \"gauge\")\n  |> keep(columns: [\"_value\", \"_time\", \"service\"])\n  |> last()\n",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    { "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 }, "content": "----" }
   ]
  }
 ]
}